### PR TITLE
first pull request for project

### PR DESCRIPTION
**Pull request by ajar67**
created jsx and api requests

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review - you've done a great job! I especially like your jsx code. I left some comments below and hope that it helps you to improve your project. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Search form input value should have black text color
    * All buttons should have pointer cursor
    * Mismatches with the mockup on 1440px https://pasteboard.co/aemqGSI53otZ.png https://pasteboard.co/dJy7LFWJXdxT.png
    * Many mismatches with the mockup on 768 viewport https://pasteboard.co/NNCbcdSTqduY.png https://pasteboard.co/wUG9KTiL8dbl.png
    * Please check and fix the main page on 320 viewport - there many mismatches from the mockup. You should check all sizes, spaces and text properties
    * `saved-articles` page has many mismatches from the mockup on 768 and 320 viewports - please check all sizes, spaces and text properties
    *  You should create a nav burger menu for header on mobile screen resolutions - please check the mockup
    * Icon inside `card___button` looks very small
    * Incorrect border color of `header__profile_saved`
    * Incorrect size of the popup window on all screen resolutions
    * popup window shouldn't have side spaces on 320 viewport
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The main page scrolls horizontally on 320px - 460px, 801px - 1200px screen resolutions (you should remove `overflow: hidden` style from `App` component, it's not a solution to fix the scrolling, you should fix it by changing the sizes and spaces of the containers)
    * The `saved-articles` page scrolls horizontally on all screen resolutions
- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * All links in the footer don't work at all
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEm elements classes outside their blocks (for example `container__home` class should be used only inside `container` block). You should fix all similar cases **throughout the project**
    * Modifiers should be used only with their base classes like `block__element block__element_modifier`. Please check and fix all similar cases **throughout the project**
    * You should check all modifiers - you can use boolean modifiers in some cases like hidden/disabled states, but all the rest modifiers should be a key-value modieirs. Please check and fix all similar cases **throughout the project**
- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * `header__profile` should be a button itself, not just a small icon
    * `search` should be a form
    * Footer should content copyright paragraph and links, not text and icons
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * the project has esling warnings

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Hover state opacity of `modal__button-reset` should apply only to cross without the area around the cross
    * Incorrect hover state of login button
    * No active state of searh form button
    * No hover state of "show more" button
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `modal__button-submit` button should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 45

**Comment by ajar67** [comment]
for my last pull request ... one of your comments 'please check and fix the main page on viewport 320px ... I think it was only messed up for you because you didn't refresh the page... since the 320 view port's jsx was different I have to switch it up a bit and I used windowWidth.. which needs to be refreshed when playing with the dimensions on a computer. If this is not alright please let me know

**Comment by ajar67** [comment]
There's a lot of corrections that I do not see on  my end due to the fact above. Sorry for the confusion! When you are on 320px if you refresh the page everything works the way it should. I am so sorry about this, let me know if you see them! Thank you!

**Comment by phoenixeliot** [comment]
I responded about how to fix the windowWidth issue in discord.

**Comment by phoenixeliot** [comment]
We resolved the resize hook working properly. Note btw @FiLLa-FaS that in Chrome-based browser on windows (or some other conditions I don't understand), resize events don't fire properly if you use the dev tools and resize only by entering a number in the simulated width, but if you drag the simulated window resize bar a tiny bit, it should make the event fire. I think this is fine to ignore for the sake of review because I believe this only shows up in this situation with the dev tools, not in real usage of the website.

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the clarification with size responce hook - and for the fixes, project looks much better! Several small issues below are left⏬. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Logout button should have transparent background
    * Show more button should have pointer cursor
    * Mismatches for main page on 768 viewport https://pasteboard.co/0sxqPqcnlYeN.png https://pasteboard.co/ii6PdsjM3Bp0.png
    * Mismatches for the main page on 320 viewport https://pasteboard.co/RO5mWItJObMo.png https://pasteboard.co/9YMpuCuTGS4D.png https://pasteboard.co/pHWSVtpmGVMS.png
    * Mismatches for `saved-articles` page on 768 viewport https://pasteboard.co/e42NjUanFFZg.png
    * Incorrect text properties of `header__title-white` and width of `modal__button-submit` in nav mobile menu
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Popup closing button shouldn't extend outside the screen on intermediate screen resolutions
    * The main page scrolls horizontally on 399px - 498px, 801px - 1233px
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEm elements classes outside their blocks (for example `preloader__section` class should be used only inside `preloader` block). **You should fix all similar cases throughout the project**
    * Modifiers should be used only with their base classes like `block__element block__element_modifier`. **Please check and fix all similar cases throughout the project**
    * You should check all modifiers - you can use boolean modifiers in some cases like hidden/disabled states, but all the rest modifiers should be a key-value modieirs. Please check and fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * You should add the eslint to the project again and fix all warnings manually one by one

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Hover state opacity of `modal__button-reset` should apply only to cross without the area around the cross
    * Incorrect hover state of login button
    * No active state of searh form button
    * No hover state of "show more" button
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `modal__button-submit` button should be highlighted when focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections - I like how your project looks! Several small issues below are left. Please note that BEM implementing has many violations from the  BEM principles - you can read more about BEM here https://en.bem.info/. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches for main page on 768 viewport https://pasteboard.co/r8KEeUONOy8e.png
    * Mismatches for main page on 320 viewport https://pasteboard.co/e8mjqXC0Q1RZ.png https://pasteboard.co/U5De4EeNU0ED.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * News cards should be centered horizontally on all intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM elements and modifiers classes outside their blocks (for example `preloader_hidden` class and `preloader__section` should be used only inside `preloader` block). **You should fix all similar cases throughout the project**
    * Modifiers should be used only with their base classes like `block__element block__element_modifier`. **Please check and fix all similar cases throughout the project**
    * You should check all modifiers - you can use boolean modifiers in some cases like hidden/disabled states, but all the rest modifiers should be a key-value modieirs. Please check and fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Hover state opacity of `modal__button-reset` should apply only to cross without the area around the cross https://pasteboard.co/vacNIjIjIb0y.png
    * Incorrect hover state of "show more" button (text shouldn't change its opacity)
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `modal__button-submit` button can't be focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 66

**Comment by ajar67** [comment]
I tested all of my code in a BEM bookmarklet and it says everything looks good. I only fixed two or three things though so I do not know if you mean something else. I triple checked all of my files and all the parent div tags are correct with the block so I am not sure exactly what else to do! Please let me know if there is more! Thank you for all your help!

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm glad to accept your project! Btw I left more detailed comments about BEM implementing and hope it will help you to check your project again and deal with BEM a little more. Congratulations and good luck on the next stage!🙌

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM elements and modifiers classes outside their blocks. For example `preloader_hidden` class should be used only inside `preloader` block, and now `preloader` block inside the `preloader_hidden` modifier. You should consider BEM block as a large independent part, and BEM elements and modifiers as parts that cannot exist outside of their block, so your page structure should consist of blocks and inside this blocks you can use BEM elements (and modifiers from blocks and elements). **You should fix all similar cases throughout the project**
    * Modifiers should be used only with their base classes like `block__element block__element_modifier` (for example `preloader_hidden` should be used only with its block like `preloader preloader_hidden`. You need to do it because we can get base styles from base block or element class and then modify them in modifier class. Please check and fix all similar cases throughout the project
    * You should check all modifiers - you can use boolean modifiers in some cases like hidden/disabled states, but all the rest modifiers should be a key-value modieirs (for example `modal__section_signin` is a boolean modifier, but it should be a key-value modifier). Please check and fix all similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Hover state opacity of `modal__button-reset` should apply only to cross without the area around the cross https://pasteboard.co/vacNIjIjIb0y.png
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
    * `modal__button-submit` button can't be focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 92

**Pull request merged**
